name: eggnstone_flutter
copyright: 2020-2021 Mark Eggenstein
description: A collection of Flutter tools, including wrappers for logging, Analytics and Crashlytics.
homepage: https://github.com/eggnstone/eggnstone_flutter
version: 0.3.6

# Default package versions on 18.02.2021
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^6.0.0
  # Internationalization
  intl: ^0.17.0
  # Version and build number
  package_info: ^2.0.0
  # Storing+retrieving settings
  shared_preferences: ^2.0.1
  # URL launcher
  url_launcher: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocking
  mockito: any
