name: eggnstone_flutter
copyright: 2020-2025 Mark Eggenstein
description: A collection of Flutter tools, including wrappers for Logging, Analytics and Crashlytics.
homepage: https://github.com/eggnstone/eggnstone_flutter
version: 4.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.3
  eggnstone_dart: ^1.3.0
  #eggnstone_dart:
  #  path: ..\eggnstone_dart
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
