name: eggnstone_flutter
copyright: 2020-2021 Mark Eggenstein
description: A collection of Flutter tools, including wrappers for logging, Analytics and Crashlytics.
homepage: https://github.com/eggnstone/eggnstone_flutter
version: 3.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^7.1.3
  # Internationalization (for logger)
  intl: ^0.17.0
  # Storing+retrieving settings
  shared_preferences: ^2.0.6
  # URL launcher
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  # Mocking
  mockito: ^5.0.10
