name: eggnstone_flutter
copyright: 2020 Mark Eggenstein
description: A collection of Flutter tools, including wrappers for logging, Analytics and Crashlytics.
homepage: https://github.com/eggnstone/eggnstone_flutter
version: 0.3.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^4.0.4
  # Internationalization
  intl: ^0.16.1
  # Storing+retrieving settings
  shared_preferences: ^0.5.10
  # URL launcher
  url_launcher: 5.5.0 # 5.5.1 has error: No named parameter with the name 'webOnlyWindowName'.
  # https://github.com/flutter/flutter/issues/64863
  # https://github.com/flutter/plugins/pull/2979#issuecomment-683304067

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocking
  mockito: ^4.1.2

flutter:
