name: eggnstone_flutter
copyright: 2020 Mark Eggenstein
description: A collection of Flutter tools.
homepage: https://eggnstone.dev
version: 0.0.6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Analytics (Web)
  firebase: ^7.2.1
  # Firebase Analytics (NonWeb)
  firebase_analytics: ^5.0.11
  # Google/Firebase Crashlytics, logging crashes
  firebase_crashlytics: ^0.1.3+3
  # Service locator
  get_it: ^4.0.1
  # Internationalization
  # beta: ^0.16.1
  # stable: 0.16.0
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocking
  mockito: ^4.1.1

flutter:
