name: eggnstone_flutter
copyright: 2020-2021 Mark Eggenstein
description: A collection of Flutter tools, including wrappers for logging, Analytics and Crashlytics.
homepage: https://github.com/eggnstone/eggnstone_flutter
version: 0.4.0-nullsafety.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^5.0.1
  # Internationalization
  intl: ^0.17.0-nullsafety.2
  # Storing+retrieving settings
  shared_preferences: ^0.5.12+4
  # URL launcher
  url_launcher: ^6.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocking
  mockito: ^4.1.3
