name: eggnstone_flutter
copyright: 2020-2025 Mark Eggenstein
description: A collection of Flutter tools, including wrappers for logging, Analytics and Crashlytics.
homepage: https://github.com/eggnstone/eggnstone_flutter
version: 4.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^8.0.3
  # For logging
  eggnstone_dart: ^1.1.1
  # Storing+retrieving settings
  shared_preferences: ^2.3.5
  # URL launcher
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Mocking
  #mockito: ^5.4.4
