name: eggnstone_flutter
copyright: 2020-2023 Mark Eggenstein
description: A collection of Flutter tools, including wrappers for logging, Analytics and Crashlytics.
homepage: https://github.com/eggnstone/eggnstone_flutter
version: 3.7.2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^7.7.0
  # For logging
  eggnstone_dart: ^1.1.0
  # Storing+retrieving settings
  shared_preferences: ^2.2.3
  # URL launcher
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Mocking
  mockito: ^5.4.4
